"""
配置包初始化
"""
from .settings import (
    BASE_DIR,
    STORAGE_DIR,
    DOCUMENTS_DIR,
    KNOWLEDGE_BASE_DIR,
    LLM_CONFIG,
    TECH_CATEGORIES,
    SUMMARY_LENGTH_CONFIG,
    RELATION_THRESHOLD,
    MAX_KEYWORDS,
    MIN_ABSTRACT_LENGTH,
    MAX_ABSTRACT_LENGTH,
    SUPPORTED_FORMATS,
    VECTOR_DB_TYPE,
    INDEXING_CONFIG
)

__all__ = [
    "BASE_DIR",
    "STORAGE_DIR",
    "DOCUMENTS_DIR",
    "KNOWLEDGE_BASE_DIR",
    "LLM_CONFIG",
    "TECH_CATEGORIES",
    "SUMMARY_LENGTH_CONFIG",
    "RELATION_THRESHOLD",
    "MAX_KEYWORDS",
    "MIN_ABSTRACT_LENGTH",
    "MAX_ABSTRACT_LENGTH",
    "SUPPORTED_FORMATS",
    "VECTOR_DB_TYPE",
    "INDEXING_CONFIG"
]